// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace axc {

public class FirstPass {

	public	Parser	parser = new Parser();
	public	Token	token  = new Token();

	public	void parseFile( string filename ) {
		var sf = new SourceFile( filename );

		var pos = new LexerPos();
		pos.sourceFile = sf;
		pos.filePos = 0;
		pos.line = 1;
		pos.col  = 1;

		parser.setPos( token, pos );

		parse_NamespaceBody();
	}

	void parse_NamespaceBody() {
		for(;;) {
			if( token.type == TokenType.EOF ) break;
			parser.skipNewLines();
			parser.nextToken();
		}
	}

}

}

