// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace axc {

public class Log {

	public	static	void Info( string msg ) {
		System.Console.Write( msg + "\n" );
	}

	public	static	void Error( LexerPos pos, string msg ) {
		Error( msg + " #"+pos.line+":"+pos.col );
	}

	public	static	void Error( string msg ) {
		System.Console.Write( "Error: " + msg + "\n" );
//		throw new Exception( msg );
	}
}
	
}

