// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace axc {

public class SourceFile {
	public	string	filename;
	public	string	sourceCode;

	public	SourceFile( string filename ) {
		this.filename = filename;

		Log.Info( "SourceFile = " + filename );
		sourceCode = System.IO.File.ReadAllText( filename, System.Text.Encoding.UTF8 );

		Compiler.instance.sourceFiles.Add( this );
	}
}

}

