// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace axc {

public enum TokenType {
	unknown = 0,
	EOF,
	identifier,
	stringLiteral,
	charLiteral,
	newline,
	number,
	comment,
	
	equals,
	equals3,

	notEquals,
	notEquals3,

	less,
	less2,

	greater,
	greater2,

	lessGreater,

	lessEquals,
	greaterEquals,

	colon,
	colon2,

	comma,
	semiColon,

	at,
	hash,
	dollar,
	backMark,
	backSlash,

	question,
	questionDot,

	exclamation,
	exclamationDot,

	add,
	sub,
	mul,
	div,
	mod,

	add2,
	sub2,
	mul2,
	div2,
	mod2,

	assign,
	colonAssign,
	addAssign,
	subAssign,
	mulAssign,
	divAssign,
	modAssign,

	roundBracketOpen,
	roundBracketClose,

	curlyBracketOpen,
	curlyBracketClose,

	squareBracketOpen,
	squareBracketClose,
}

public class Token {
	public	TokenType	type;
	public	string		str;
	public	LexerPos	pos;

	public void Set( TokenType type, string str ) {
		this.type	= type;
		this.str	= str;
	}

	public override string ToString () {
		return string.Format ("Token = [{0}] {1}:{2}", str, pos.line, pos.col );
	}
}

}

